A52HackTool: firecode.h File Reference
firecode.h File Reference
Specification of first encoding phase: Fire code (CRC)
#include "const_code.h"
Functions
void processFireGMatrix (byte G[FIRE_SOURCE_LENGTH][FIRE_CODE_LENGTH])
Calculates the encoding matrix corresponding to the Fire encoding step.
void processFireHMatrix (byte H[FIRE_CRC_LENGTH][FIRE_CODE_LENGTH], byte G[FIRE_SOURCE_LENGTH][FIRE_CODE_LENGTH])
Calculates the parity-check matrix H corresponding to the Fire encoding step from the Fire encoding matrix G.
void reverseFire (byte in[FIRE_CODE_LENGTH], byte out[FIRE_SOURCE_LENGTH])
Decodes a previously Fire-encoded message.
Detailed Description
Specification of first encoding phase: Fire code (CRC)
Author:
Nicolas Paglieri & Olivier Benjamin
Version:
File Revision #9
Date:
24/06/2011
Function Documentation
void processFireGMatrix (byte G[FIRE_SOURCE_LENGTH][FIRE_CODE_LENGTH])
Calculates the encoding matrix corresponding to the Fire encoding step.
Parameters:
[out] G Fire encoding matrix
References FIRE_CODE_LENGTH, FIRE_SOURCE_LENGTH, and polynomial_mirrored.
Referenced by processFullEncodingGMatrix(), and reverseFire().
void processFireHMatrix (byte H[FIRE_CRC_LENGTH][FIRE_CODE_LENGTH], byte G[FIRE_SOURCE_LENGTH][FIRE_CODE_LENGTH])
Calculates the parity-check matrix H corresponding to the Fire encoding step from the Fire encoding matrix G.
Parameters:
[out] H Fire parity-check matrix
[in] G Fire encoding matrix
References FIRE_CRC_LENGTH, and FIRE_SOURCE_LENGTH.
Referenced by reverseFire().
void reverseFire (byte in[FIRE_CODE_LENGTH], byte out[FIRE_SOURCE_LENGTH])
Decodes a previously Fire-encoded message.
Parameters:
[in] in Fire-encoded data to decode
[out] out Decoded data
References DEBUG_INFO, DUMP_CHAR_VECTOR, FIRE_CODE_LENGTH, FIRE_CRC_LENGTH, FIRE_SOURCE_LENGTH, processFireGMatrix(), and processFireHMatrix().
Referenced by processFullDecoding().